services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/musichub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_THYMELEAF_CACHE: false

      BUCKET_NAME: artist-photos
      ENDPOINT: http://localhost:9000
      ACCESS_KEY: myaccesskey
      SECRET_KEY: mysecretkey
      SECRET_JWT: secretKeyForJWTToken
      SPRING_RABBITMQ_HOST: localhost
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: musichub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: